### ISSUE TITLE
Upload artifact to Maven

### ISSUE THREAD

**Issue by goober** [goober/coordinate-transformation-library#2]
Upload artifacts to Sonatype's OSSRH repository.

For instructions see: 
https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide

**Comment by thallgren** [comment]
Are there any plans to go ahead and upload this component?

**Comment by tomasbjerre** [comment]
I created a PR for this. See https://github.com/goober/coordinate-transformation-library/pull/7

If no response here, I will release my fork to Maven Central.

**Comment by goober** [comment]
http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22coordinate-transformation-library%22
